package com.jmzc.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-08-17T12:53:46.468+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebServiceClient(name = "TestEndPointService", 
                  wsdlLocation = "http://localhost:8080/ws-0.0.1-SNAPSHOT/TestEndPoint?wsdl",
                  targetNamespace = "http://server.jmzc.com/") 
public class TestEndPointService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://server.jmzc.com/", "TestEndPointService");
    public final static QName TestEndPointPort = new QName("http://server.jmzc.com/", "TestEndPointPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/ws-0.0.1-SNAPSHOT/TestEndPoint?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TestEndPointService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/ws-0.0.1-SNAPSHOT/TestEndPoint?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TestEndPointService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestEndPointService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestEndPointService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TestEndPointService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TestEndPointService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TestEndPointService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TestEndPoint
     */
    @WebEndpoint(name = "TestEndPointPort")
    public TestEndPoint getTestEndPointPort() {
        return super.getPort(TestEndPointPort, TestEndPoint.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TestEndPoint
     */
    @WebEndpoint(name = "TestEndPointPort")
    public TestEndPoint getTestEndPointPort(WebServiceFeature... features) {
        return super.getPort(TestEndPointPort, TestEndPoint.class, features);
    }

}
