package com.jmzc.client;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.4.6
 * 2012-08-17T12:53:46.406+02:00
 * Generated source version: 2.4.6
 * 
 */
@WebService(targetNamespace = "http://server.jmzc.com/", name = "TestEndPoint")
@XmlSeeAlso({ObjectFactory.class})
public interface TestEndPoint {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getUser", targetNamespace = "http://server.jmzc.com/", className = "com.jmzc.client.GetUser")
    @WebMethod
    @ResponseWrapper(localName = "getUserResponse", targetNamespace = "http://server.jmzc.com/", className = "com.jmzc.client.GetUserResponse")
    public java.lang.String getUser();
}
