
package com.jmzc.server.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 2.4.6
 * Tue Sep 11 09:16:07 CEST 2012
 * Generated source version: 2.4.6
 */

@XmlRootElement(name = "getUser", namespace = "http://server.jmzc.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getUser", namespace = "http://server.jmzc.com/")

public class GetUser {


}

